Fix missing symbol at ImsPhoneCallTracker.java
frameworks/opt/telephony/src/java/com/android/internal/telephony/imsphone/ImsPho
neCallTracker.java:325: error: cannot find symbol
            final boolean shouldBlockBinderThreadOnIncomingCalls = SystemPropert
ies.getBoolean(
                                                                   ^
  symbol:   variable SystemProperties
  location: class ImsPhoneCallTracker.MmTelFeatureListener
1 error

Signed-off-by: CrisBal <crisbaladim@yahoo.gr>
Signed-off-by: rajkale99 <kaleraj.rk@gmail.com>